import localFont from "next/font/local";
import DepartmentNavbar from "@/components/departments/department_navbar";
// import "./globals.css";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function ComputerScienceLayout({ children }) {
    return (

        <div className = "department">
        
        { children }
        
        </div>
    );
}
